### ISSUE TITLE
v2.91 Large - keep alive not working

### ISSUE THREAD

**Issue by dominikfe** [victronenergy/dbus-mqtt#16]
Hi!
I am trying to get mqtt messages by either sending R/xxx/keepalive or R/xxx/system/0/Serial to the mqqt broker of Venus OS but neither a Serial, nor any other data is published after that.
Is mqtt broken in 2.91 Large?
THX!

**Comment by dominikfe** [comment]
In the meantime I checked the logs and found the following in /var/log/dbus-mqtt/current:
```
@40000000633975f8171416b4 Traceback (most recent call last):
@40000000633975f81717471c   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 397, in _scan_dbus_service
@40000000633975f8173c18e4     items = self._get_dbus_value(service, '/')
@40000000633975f81740c04c   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 533, in _get_dbus_value
@40000000633975f81766f974     return self._dbus_conn.call_blocking(service, path, None, 'GetValue', '', [])
@40000000633975f8176c19f4   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
@40000000633975f81798fe24     reply_message = self.send_message_with_reply_and_block(
@40000000633975f8179da974 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Unknown / invalid method
@40000000633975f817a7139c 
@40000000633975f817a71784 During handling of the above exception, another exception occurred:
@40000000633975f817a72b0c 
@40000000633975f817a8ec44 Traceback (most recent call last):
@40000000633975f817aaccbc   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 602, in <module>
@40000000633975f817d2d6bc     main()
@40000000633975f817d7438c   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 584, in main
@40000000633975f818000cf4     handler = DbusMqtt(
@40000000633975f8180521bc   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 217, in __init__
@40000000633975f81818a5d4     self._scan_dbus_service(service)
@40000000633975f8181d0ad4   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 401, in _scan_dbus_service
@40000000633975f81838d804     self._introspect(service, device_instance, '/', publish)
@40000000633975f8183d3534   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 441, in _introspect
@40000000633975f8185ab014     self._introspect(service, device_instance, p, publish=publish)
@40000000633975f8185f0d44   File "/opt/victronenergy/dbus-mqtt/dbus_mqtt.py", line 423, in _introspect
@40000000633975f8187cda2c     value = self._dbus_conn.call_blocking(service, path, None, 'Introspect', '', [])
@40000000633975f818819904   File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
@40000000633975f818ad777c     reply_message = self.send_message_with_reply_and_block(
@40000000633975f818b1c8f4 dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Unknown / invalid method
```

**Comment by mpvader** [comment]
Hi, that error can be perfectly normal.

i’m 99.99% sure that mqtt works fine on venus os large. If not we’d have known by now.

One way to check is is to open VRM and see if Real time mode works on the dashboard

I’ll close this issue: we don’t do support here in the tracker, sorry for that. Please go to the Modifications section on Community. See our wiki here in this repo and/or readme.

thanks.

**Comment by mpvader** [comment]
Ps: I noticed that there was no link in the readme. Updated now, and here is where to go with support and other questions.

https://community.victronenergy.com/spaces/31/mods.html

success!
